---
title: "Training Load"
author: "Dominik Rappaport"
date: "2025-08-03"
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}

# Load libraries ----------------------------------------------------------

library("tidyverse")
library("lubridate")
library("bbplot")
library("scales")
library(knitr)

# Read from files ---------------------------------------------------------

tl <- read_csv("../data/processed/trainingload.csv")

# Reformat table ----------------------------------------------------------

tl <- tl %>%
  mutate(
    date = as.Date(date, format = "%d.%m.%y"), 
    year = as.factor(year(date)),
    month = as.factor(month(date)),
    week  = as.factor(isoweek(date)),
    day = as.factor(day(date)),
    duration = as.numeric(hms(duration), units="hours"),
    date2 = as.Date(paste0("2001", "-", month, "-", day)))

```

# Trainingsstatistiken

Übersicht über Trainingsstunden, TSS und CTL für die Jahre 2020 bis 2025. Als Zeitraum zum Berechnen des Durchschnitts wurden alle Wochen des Jahres herangezogen und nicht nur die, an denen ein Training grundsätzlich möglich war. D. h., Urlaube, Krankenstände, Dienstreisen usw. drücken den Schnitt.

```{r, echo=FALSE}
yearly_statistics <- tl %>% 
  group_by(year) %>%
  summarise(
    `Trainingsstunden` = round(sum(duration, na.rm = TRUE)),
    `Trainingsstunden pro Woche (Ø)` = round(sum(duration, na.rm = TRUE) / 365 * 7, 2),
    `TSS` = sum(TSS, na.rm = TRUE),
    `TSS pro Woche (Ø)` = round(sum(TSS, na.rm = TRUE) / 365 * 7),
    `CTL (Ø)` = round(mean(CTL, na.rm = TRUE)),
  ) %>%
  rename(Jahr = year)
kable(yearly_statistics, caption = "Trainingsstatistik")
```

```{r, echo=FALSE, fig.height=30, warning=FALSE}
tl %>%
  ggplot(aes(x = date2, y = CTL)) +
  geom_line(colour = "#1380A1", linewidth = 1) +
  geom_hline(yintercept = 0,
             linewidth = 1,
             colour = "#333333") +
  scale_x_date(
    date_labels = "%b"
  ) +
  scale_y_continuous(
    limits = c(0, 80),
    breaks = seq(0, 80, 10),
  ) +
  facet_wrap(~ year, ncol = 1) +
  bbc_style() +
  labs(title = "Chronische Trainingslast (CTL)")
```
